name: 'update-game-files'
on: push

jobs:    
  check_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: clone Pseudo-Corp/SynergismOfficial
        run: |
          git clone https://github.com/Pseudo-Corp/SynergismOfficial
          cd SynergismOfficial
          git checkout gh-pages
          cd ..
      - name: Update files
        run: |
          rm -rf ./src
          mkdir src
          mv SynergismOfficial/Pictures SynergismOfficial/dist SynergismOfficial/Synergism.css SynergismOfficial/favicon.ico SynergismOfficial/index.html ./src
          
          echo running git status
          git status --porcelain
          echo done

          if [[ `git status --porcelain` ]]; then
            git config user.name "KhafraDev"
            git config user.email "maitken033380023@gmail.com"
            git add src
            git commit -m "Update Synergism"
            git push
          else
            echo no changes
          fi
      - name: Cleanup
        run: |
          rm -rf SynergismOfficial

